/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oberonguinetbeans;

/**
 *
 * @author rafaelhernandez
 */
public class editWorkTaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form editWorkTask
     */
    public editWorkTaskFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editWorkTasksLabel = new javax.swing.JLabel();
        workEditTitleLabel = new javax.swing.JLabel();
        workEditDateLabel = new javax.swing.JLabel();
        workEditPriorityLabel = new javax.swing.JLabel();
        workEditProjNameLabel = new javax.swing.JLabel();
        workEditMeetWLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editworkTitleField = new javax.swing.JTextField();
        editWorkDateField = new javax.swing.JTextField();
        workEditProjNField = new javax.swing.JTextField();
        workEditMeetWField = new javax.swing.JTextField();
        workEditHoursLabel = new javax.swing.JTextField();
        updateWorkTaskB = new javax.swing.JButton();
        editWorkPriority = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);

        editWorkTasksLabel.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        editWorkTasksLabel.setForeground(new java.awt.Color(150, 0, 51));
        editWorkTasksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editWorkTasksLabel.setText("Edit Work Tasks");

        workEditTitleLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        workEditTitleLabel.setText("Title ");

        workEditDateLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        workEditDateLabel.setText("Date");

        workEditPriorityLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        workEditPriorityLabel.setText("Priority");

        workEditProjNameLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        workEditProjNameLabel.setText("Project Name");

        workEditMeetWLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        workEditMeetWLabel.setText("Meeting With");

        jLabel7.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel7.setText("Hours Worked");

        editworkTitleField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editworkTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editworkTitleFieldActionPerformed(evt);
            }
        });

        editWorkDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editWorkDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWorkDateFieldActionPerformed(evt);
            }
        });

        workEditProjNField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        workEditMeetWField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        workEditHoursLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        updateWorkTaskB.setText("Update Task");
        updateWorkTaskB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateWorkTaskB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWorkTaskBActionPerformed(evt);
            }
        });

        editWorkPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        editWorkPriority.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workEditMeetWField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workEditProjNField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editWorkDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(workEditDateLabel)
                                .addComponent(workEditTitleLabel)
                                .addComponent(workEditPriorityLabel)
                                .addComponent(workEditProjNameLabel)
                                .addComponent(workEditMeetWLabel)
                                .addComponent(jLabel7)
                                .addComponent(editworkTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(workEditHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editWorkPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(updateWorkTaskB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(editWorkTasksLabel)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(editWorkTasksLabel)
                .addGap(18, 18, 18)
                .addComponent(workEditTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editworkTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workEditDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editWorkDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(workEditPriorityLabel)
                .addGap(2, 2, 2)
                .addComponent(editWorkPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workEditProjNameLabel)
                .addGap(1, 1, 1)
                .addComponent(workEditProjNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workEditMeetWLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workEditMeetWField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workEditHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateWorkTaskB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editworkTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editworkTitleFieldActionPerformed
        // TODO add your handling code here:
        // leave alone unless needed, or erase
    }//GEN-LAST:event_editworkTitleFieldActionPerformed

    private void editWorkDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWorkDateFieldActionPerformed
        // TODO add your handling code here:
        // leave alone unless needed, or erase  
    }//GEN-LAST:event_editWorkDateFieldActionPerformed

    private void updateWorkTaskBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWorkTaskBActionPerformed
        // TODO add your handling code here:
        // When update is pressed on edit work task frame, task should be updated, and the edit work task window should close without ending the program. 
        // recommended to use xxxxx.setDefaultCloseOperation(DISPOSE_ON_CLOSE); command on update button. or something similar
        
    }//GEN-LAST:event_updateWorkTaskBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editWorkTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editWorkTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editWorkTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editWorkTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editWorkTaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editWorkDateField;
    private javax.swing.JComboBox<String> editWorkPriority;
    private javax.swing.JLabel editWorkTasksLabel;
    private javax.swing.JTextField editworkTitleField;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateWorkTaskB;
    private javax.swing.JLabel workEditDateLabel;
    private javax.swing.JTextField workEditHoursLabel;
    private javax.swing.JTextField workEditMeetWField;
    private javax.swing.JLabel workEditMeetWLabel;
    private javax.swing.JLabel workEditPriorityLabel;
    private javax.swing.JTextField workEditProjNField;
    private javax.swing.JLabel workEditProjNameLabel;
    private javax.swing.JLabel workEditTitleLabel;
    // End of variables declaration//GEN-END:variables
}
