/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oberonguinetbeans;

import CoreCode.TaskController;
import CoreCode.TaskType;

import java.util.Vector;

/**
 *
 * @author rafaelhernandez
 */
public class editSocialTaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form editSocialTaskFrame
     */
    public editSocialTaskFrame(Vector<String> dataFields, TaskController C)
    {
        initComponents();
        editSocialTitleField.setText(dataFields.get(0));
        editSocialdateField.setText(dataFields.get(1));
        editSocialPriority.setSelectedIndex(Integer.parseInt(dataFields.get(3))-1);
        editOccasionField.setText(dataFields.get(4));
        editSocialLocField.setText(dataFields.get(5));
        editAttendingHours.setText(dataFields.get(6));
        this.C = C;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editSocialTaskLabel = new javax.swing.JLabel();
        socialEditTitleLabel = new javax.swing.JLabel();
        socialEditDateLabel = new javax.swing.JLabel();
        socialEditPriorityLabel = new javax.swing.JLabel();
        socialEditMeetLocLabel = new javax.swing.JLabel();
        socialEditOccasionLabel = new javax.swing.JLabel();
        socialEditAttenHoursLabel = new javax.swing.JLabel();
        editSocialPriority = new javax.swing.JComboBox<>();
        editSocialTitleField = new javax.swing.JTextField();
        editSocialdateField = new javax.swing.JTextField();
        editSocialLocField = new javax.swing.JTextField();
        editOccasionField = new javax.swing.JTextField();
        editAttendingHours = new javax.swing.JTextField();
        updateWorkTaskB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editSocialTaskLabel.setText("Edit Social tasks");

        socialEditTitleLabel.setText("Title");

        socialEditDateLabel.setText("Date");

        socialEditPriorityLabel.setText("Priority");

        socialEditMeetLocLabel.setText("Meeting Location");

        socialEditOccasionLabel.setText("Occasion");

        socialEditAttenHoursLabel.setText("Attending Hours");

        editSocialPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        editSocialPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSocialPriorityActionPerformed(evt);
            }
        });

        updateWorkTaskB.setText("Update Task");
        updateWorkTaskB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWorkTaskBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(editSocialTaskLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(socialEditDateLabel)
                            .addComponent(socialEditTitleLabel)
                            .addComponent(socialEditPriorityLabel)
                            .addComponent(socialEditMeetLocLabel)
                            .addComponent(socialEditOccasionLabel)
                            .addComponent(socialEditAttenHoursLabel)
                            .addComponent(editSocialPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editSocialdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editSocialLocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editOccasionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editAttendingHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editSocialTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateWorkTaskB)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(editSocialTaskLabel)
                .addGap(17, 17, 17)
                .addComponent(socialEditTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSocialTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(socialEditDateLabel)
                .addGap(3, 3, 3)
                .addComponent(editSocialdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(socialEditPriorityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSocialPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(socialEditMeetLocLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSocialLocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(socialEditOccasionLabel)
                .addGap(2, 2, 2)
                .addComponent(editOccasionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(socialEditAttenHoursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editAttendingHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateWorkTaskB)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSocialPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSocialPriorityActionPerformed
        // TODO add your handling code here:
        // ignore or delete, not needed
    }//GEN-LAST:event_editSocialPriorityActionPerformed

    private void updateWorkTaskBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWorkTaskBActionPerformed
        // TODO add your handling code here:
        Vector<String> dataFields = new Vector<String>();
        dataFields.add(editSocialTitleField.getText());
        dataFields.add(editSocialdateField.getText());
        dataFields.add(String.valueOf((editSocialPriority.getSelectedIndex()+1)));
        dataFields.add(editOccasionField.getText());
        dataFields.add(editSocialLocField.getText());
        dataFields.add(editAttendingHours.getText());
        C.editTask(TaskType.SOCIAL, dataFields);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_updateWorkTaskBActionPerformed

    /**
     * @param args the command line arguments
     */
    TaskController C;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editAttendingHours;
    private javax.swing.JTextField editOccasionField;
    private javax.swing.JTextField editSocialLocField;
    private javax.swing.JComboBox<String> editSocialPriority;
    private javax.swing.JLabel editSocialTaskLabel;
    private javax.swing.JTextField editSocialTitleField;
    private javax.swing.JTextField editSocialdateField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel socialEditAttenHoursLabel;
    private javax.swing.JLabel socialEditDateLabel;
    private javax.swing.JLabel socialEditMeetLocLabel;
    private javax.swing.JLabel socialEditOccasionLabel;
    private javax.swing.JLabel socialEditPriorityLabel;
    private javax.swing.JLabel socialEditTitleLabel;
    private javax.swing.JButton updateWorkTaskB;
    // End of variables declaration//GEN-END:variables
}
