/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oberonguinetbeans;

/**
 *
 * @author rafaelhernandez
 */
public class editSchoolTaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form editSchoolTaskFrame
     */
    public editSchoolTaskFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        schoolTaskLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        SchoolHWLabel = new javax.swing.JLabel();
        studyHoursLabel = new javax.swing.JLabel();
        editSchoolPriority = new javax.swing.JComboBox<>();
        schoolPriorityLabel = new javax.swing.JLabel();
        editSchoolTitleField = new javax.swing.JTextField();
        editSchoolDateField = new javax.swing.JTextField();
        editSchoolCourseField = new javax.swing.JTextField();
        editSchoolHWField = new javax.swing.JTextField();
        editSchoolStudyHField = new javax.swing.JTextField();
        updateSchoolTask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 0, 51));
        jLabel1.setText("Edit School Task");

        schoolTaskLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        schoolTaskLabel.setText("Title");

        jLabel3.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel3.setText("Date");

        courseNameLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        courseNameLabel.setText("Course Name");

        SchoolHWLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        SchoolHWLabel.setText("HW Name");

        studyHoursLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        studyHoursLabel.setText("Study Hours");

        editSchoolPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        editSchoolPriority.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editSchoolPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSchoolPriorityActionPerformed(evt);
            }
        });

        schoolPriorityLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        schoolPriorityLabel.setText("Priority");

        editSchoolTitleField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editSchoolTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSchoolTitleFieldActionPerformed(evt);
            }
        });

        editSchoolDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        editSchoolDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSchoolDateFieldActionPerformed(evt);
            }
        });

        editSchoolStudyHField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSchoolStudyHFieldActionPerformed(evt);
            }
        });

        updateSchoolTask.setText("Update Task");
        updateSchoolTask.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateSchoolTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSchoolTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateSchoolTask)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(courseNameLabel)
                            .addComponent(SchoolHWLabel)
                            .addComponent(studyHoursLabel)
                            .addComponent(editSchoolPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolTaskLabel)
                            .addComponent(schoolPriorityLabel)
                            .addComponent(editSchoolCourseField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(editSchoolTitleField)
                            .addComponent(editSchoolDateField)
                            .addComponent(editSchoolHWField)
                            .addComponent(editSchoolStudyHField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(schoolTaskLabel)
                .addGap(1, 1, 1)
                .addComponent(editSchoolTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSchoolDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schoolPriorityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSchoolPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSchoolCourseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SchoolHWLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSchoolHWField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studyHoursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSchoolStudyHField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateSchoolTask, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSchoolPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSchoolPriorityActionPerformed
        // TODO add your handling code here:
        // ignore unless needed, can delet
    }//GEN-LAST:event_editSchoolPriorityActionPerformed

    private void editSchoolDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSchoolDateFieldActionPerformed
        // TODO add your handling code here:
       // ignore unless needed, can delete
    }//GEN-LAST:event_editSchoolDateFieldActionPerformed

    private void editSchoolTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSchoolTitleFieldActionPerformed
        // TODO add your handling code here:
        // ignore unless needed can delete
    }//GEN-LAST:event_editSchoolTitleFieldActionPerformed

    private void editSchoolStudyHFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSchoolStudyHFieldActionPerformed
        // TODO add your handling code here:
       // ignore unless needed can delete
                
    }//GEN-LAST:event_editSchoolStudyHFieldActionPerformed

    private void updateSchoolTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSchoolTaskActionPerformed
        // TODO add your handling code here:
        /// When update is pressed on edit social task frame, task should be updated, and the edit school task window should close without ending the program. 
        // recommended to use xxxxx.setDefaultCloseOperation(DISPOSE_ON_CLOSE); command on update button. or something similar
        
    }//GEN-LAST:event_updateSchoolTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editSchoolTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editSchoolTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editSchoolTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editSchoolTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editSchoolTaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SchoolHWLabel;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField editSchoolCourseField;
    private javax.swing.JTextField editSchoolDateField;
    private javax.swing.JTextField editSchoolHWField;
    private javax.swing.JComboBox<String> editSchoolPriority;
    private javax.swing.JTextField editSchoolStudyHField;
    private javax.swing.JTextField editSchoolTitleField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel schoolPriorityLabel;
    private javax.swing.JLabel schoolTaskLabel;
    private javax.swing.JLabel studyHoursLabel;
    private javax.swing.JButton updateSchoolTask;
    // End of variables declaration//GEN-END:variables
}
