/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oberonguinetbeans;

import java.util.Vector;

/**
 *
 * @author rafaelhernandez
 */
public class viewSchoolTask extends javax.swing.JFrame {

    /**
     * Creates new form viewSchoolTask
     */
    public viewSchoolTask(Vector<String> dataFields)
    {
        initComponents();
        viewSchoolTitleField.setText(dataFields.get(0));
        viewSchoolDateField.setText(dataFields.get(1));
        viewSchoolTypeField.setText(dataFields.get(2));
        viewSchoolPriorityField.setText(dataFields.get(3));
        viewSchoolCourseField.setText(dataFields.get(4));
        viewSchoolHWNameField.setText(dataFields.get(5));
        viewSchoolStudyHField.setText(dataFields.get(6));
        viewSchoolTitleField.setEditable(false);
        viewSchoolDateField.setEditable(false);
        viewSchoolTypeField.setEditable(false);
        viewSchoolPriorityField.setEditable(false);
        viewSchoolCourseField.setEditable(false);
        viewSchoolHWNameField.setEditable(false);
        viewSchoolStudyHField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewSchoolTitleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        viewSchoolDateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        viewSchoolPriorityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        viewSchoolTypeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        viewSchoolCourseField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        viewSchoolHWNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        viewSchoolStudyHField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 0, 51));
        jLabel1.setText("View School Tasks");

        jLabel2.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel2.setText("Title ");

        viewSchoolTitleField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel3.setText("Date");

        viewSchoolDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel4.setText("Priority");

        viewSchoolPriorityField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel5.setText("Type");

        viewSchoolTypeField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        viewSchoolTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSchoolTypeFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel6.setText("Course Name");

        viewSchoolCourseField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        viewSchoolCourseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSchoolCourseFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel8.setText("HW Name");

        viewSchoolHWNameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel9.setText("Study Hours");

        viewSchoolStudyHField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        viewSchoolStudyHField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSchoolStudyHFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(viewSchoolTitleField)
                                .addComponent(viewSchoolDateField)
                                .addComponent(viewSchoolPriorityField)
                                .addComponent(viewSchoolTypeField)
                                .addComponent(viewSchoolCourseField)
                                .addComponent(viewSchoolHWNameField)
                                .addComponent(viewSchoolStudyHField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolPriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolCourseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolHWNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchoolStudyHField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSchoolTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSchoolTypeFieldActionPerformed
        // TODO add your handling code here:
        // ignore
        
    }//GEN-LAST:event_viewSchoolTypeFieldActionPerformed

    private void viewSchoolCourseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSchoolCourseFieldActionPerformed
        // TODO add your handling code here:
        // ignore
        
    }//GEN-LAST:event_viewSchoolCourseFieldActionPerformed

    private void viewSchoolStudyHFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSchoolStudyHFieldActionPerformed
        // TODO add your handling code here: // ignore
        
    }//GEN-LAST:event_viewSchoolStudyHFieldActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField viewSchoolCourseField;
    private javax.swing.JTextField viewSchoolDateField;
    private javax.swing.JTextField viewSchoolHWNameField;
    private javax.swing.JTextField viewSchoolPriorityField;
    private javax.swing.JTextField viewSchoolStudyHField;
    private javax.swing.JTextField viewSchoolTitleField;
    private javax.swing.JTextField viewSchoolTypeField;
    // End of variables declaration//GEN-END:variables
}
